# Schema for the configuration files of the Practice module.
practice.settings:
  type: config_object
  label: 'Site Information'
  mapping:
    siteapikey:
      type: string
      label: 'Site API Key'
